### ISSUE TITLE
orca.cmd generated on Windows 10 has a path name mixing \ and /

### ISSUE THREAD

**Issue by BoundaryValueProblems** [plotly/orca#136] opened 2018-09-29 19:10 UTC
I don't have any problem of installing orca on Mac OS X and Linux machines, but on my Windows 10 machine, when I install orca via conda, it creates a file ```orca.cmd```, whose contents are:
```
@echo off
"/opt/anaconda1anaconda2anaconda3\orca_app\orca.exe" %*
```
This mixed use of ```/``` and ```\``` is not good and doesn't work on windows.
On Mac OS X and Linux, only ```/``` is used. Which file should be fixed for Windows machines?
Thanks for your help!

**Comment by jonmmease** [comment] 2018-10-05 00:00
Sure, from the command prompt run

```
conda --version
```
I'm not familiar with the Conda.jl project, but here's an old PR that looks like it was designed to fix an issue very similar to what you're seeing. https://github.com/JuliaPy/Conda.jl/pull/9

Oh, and what is the full path to the `orca.cmd` file you mentioned above?  I'm wondering if somehow your environment is picking up the `orca.cmd` file in the `pkgs` directory, rather than the one under `/path/to/env/bin/orca.cmd`

**Comment by BoundaryValueProblems** [comment] 2018-10-05 03:36
@jonmmease: Thanks! The version of conda on my windows machine is 4.5.11. Now, to be more precise, plotly/orca was installed by ORCA.jl: https://github.com/sglyon/ORCA.jl, which in turn uses Conda.jl.
On my windows machine, ```orca.cmd``` was installed on the folder: ```/c/Users/My Username/.julia/packages/ORCA/vWe2Y/deps``` and its contents is:
```
@echo off
"C:/Users/My Username/.julia/packages/ORCA/vWe2Y/deps\orca_app\orca.exe" %*
```
The ```orca.cmd``` containing the line ```"/opt/anaconda1anaconda2anaconda3\orca_app\orca.exe" %*``` that I mentioned in my first posting is actually in the folder ```/c/Users/My Username/.julia/packages/Conda/hsaaN/deps/usr/pkgs/plotly-orca-1.1.1-1```, which also seems to be installed by Conda.jl via ORCA.jl. Thanks for your help!

**Comment by jonmmease** [comment] 2018-10-05 10:46
Hi @BoundaryValueProblems ,

With conda packages you (and other libraries) shouldn't use scripts under the `pkgs` directory, because conda does important stuff during the installation process (like rewriting the `/opt/anaconda1anaconda2anaconda3` string), when things are moved to the environment directory.  So in your case, you shouldn't directly call the `orca.cmd` script in `/c/Users/My Username/.julia/packages/Conda/hsaaN/deps/usr/pkgs/plotly-orca-1.1.1-1`.  Instead you probably need to call the one in `/c/Users/My Username/.julia/packages/ORCA/vWe2Y/deps`.

Does that help?

If `ORCA.jl` is calling the orca script under `pkgs/` for you them we might need to bring this up in that repo

**Comment by BoundaryValueProblems** [comment] 2018-10-05 17:35
@jonmmease: Sorry for the confusion, but ```orca.cmd``` installed by ```ORCA.jl``` is the one used. I just simply cited the version under ```pkgs/plotly-orca-1.1.1-1``` to draw people's attention because both ```orca.cmd``` files have problems like my original posting at least under Windows. By the way, I tried to reinstall ```plotly/orca``` via ```ORCA.jl``` from scratch. But the problem still remains: nothing has changed so far.

**Comment by jonmmease** [comment] 2018-10-06 11:10
Hi @BoundaryValueProblems,  I'm not sure I'm following your whole situation anymore.  Let me summarize.

The `orca.cmd` file under `C:/Users/My Username/.julia/packages/Conda/hsaaN/deps/usr/pkgs/plotly-orca-1.1.1-1` that contains the `/opt/anaconda1anaconda2anaconda3` string is installed by conda.  It is the expected behavior for this script to contain the `/opt/anaconda1anaconda2anaconda3` string, and this script should *not* be called directly.

The `orca.cmd` file under `C:/Users/My Username/.julia/packages/ORCA/vWe2Y/deps` is the one that conda creates during the installation process and this is the one that is intended to be executed by users.  This script should not have the `/opt/anaconda1anaconda2anaconda3` string anymore.

What error are you seeing when you run the orca.cmd script under `C:/Users/My Username/.julia/packages/ORCA/vWe2Y/deps`?

Also, what shell are you using for testing this?  The paths starting with `/c/Users...` aren't standard windows paths, so perhaps something is getting mixed up there.

**Comment by BoundaryValueProblems** [comment] 2018-10-06 17:50
@jonmmease: Thanks! What you summarized were correct. I just want to add that both ```orca.cmd``` contains the paths mixing ```/``` and ```\```.

Now if I run the original ```orca.cmd``` that contains the path mixing ```/``` and ```\``` in ```C:\Users\My Username\.julia\packages\ORCA\vWe2Y\deps``` under git-bash or CMD terminal, I got the following, which sounds right:
```
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`.
```
Of course I got the same output if I replace ```/``` by ```\``` in ```orca.cmd```.
So, after all, don't I need to worry about those mixing ```/``` and ```\```?

**Comment by Clocktown** [comment] 2018-11-22 20:34
Windows can handle a mix and match of `/` and `\`. This wasn't always true. Nowadays, you don't need to worry.

**Comment by jonmmease** [comment] 2018-12-03 11:21
Closing as it seems like the original issue here was resolved. Feel free to follow up if that's not the case.

**Closed by jonmmease** 2018-12-03 11:21 UTC
