### ISSUE TITLE
(some PDF viewers) Orca using plotly.js > 1.49.5 creates thin lines for bars with 0 length

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/orca#345] opened 2020-08-17 14:29 UTC
0-length bars are visible in pdfs generated by Orca even though they aren't visible in the plotly.js graphs.

<img width="742" alt="image001" src="https://user-images.githubusercontent.com/41019918/90187985-b4fd2080-dd88-11ea-9c69-a12b32672416.png">

I can reproduce this issue using orca directly using [this method](https://github.com/plotly/orca/issues/187#issuecomment-515546339) with the below json figure.

```
{"data": [{"y": ["This", "is", "a", "test", "placeholder"], "x": [12, 9, 15, 12, 0], "type": "bar", "orientation": "h"}], "layout": {"xaxis": {"type": "categorical", "showgrid": false, "zeroline": false}, "yaxis": {"title": "test", "zeroline": false}}}
```

**Comment by michaelbabyn** [comment] 2020-08-17 14:33
Note that the issue doesn't appear when I look at the pdf using Ubuntu's built in document viewer but it does appear when I open the PDF if chrome.

[fig.pdf](https://github.com/plotly/orca/files/5084857/fig.pdf)

**Comment by cldougl** [comment] 2020-08-19 15:58
cc @plotly/product

**Comment by nicolaskruchten** [comment] 2020-08-20 01:24
@antoinerg can you take a look plz?

**Comment by archmoj** [comment] 2020-08-20 15:57
The v1.49.5 changelog is here: https://github.com/plotly/plotly.js/releases/tag/v1.49.5
What is the last `plotly.js` version that this works fine? Is that v1.49.4?

**Comment by michaelbabyn** [comment] 2020-08-20 16:01
@archmoj 1.49.5 works and 1.50.0 is the first version that fails

**Comment by archmoj** [comment] 2020-08-20 16:05
Is this only problematic when the zero bars are on sides of the graph, not in the middle?

**Comment by michaelbabyn** [comment] 2020-08-20 16:13
When the zero bars are in the middle on 1.50.0, the line appears before saving the chart to a PDF https://codepen.io/michaelbabyn/pen/xxVRbjY

**Comment by michaelbabyn** [comment] 2020-08-20 16:14
Note that I can reproduce the issue by printing the page to PDF using chrome if that makes debugging easier

**Comment by archmoj** [comment] 2020-08-20 16:16
Here is v1.50.0 changelog: https://github.com/plotly/plotly.js/releases/tag/v1.50.0
Might be related to these PRs: https://github.com/plotly/plotly.js/pull/4180 and https://github.com/plotly/plotly.js/pull/4186

**Comment by antoinerg** [comment] 2020-08-20 20:47
Thanks for the references @archmoj!

The reason why plotly.js puts a bar with a width of 0 is to properly support transitions. We can't transition a bar from being non-existent to having a finite value. That's the conclusion I reached anyway when introducing https://github.com/plotly/plotly.js/pull/4180.

It looks like a Chromium bug to me that rectangles with zero width would appear in its PDF output. Anyway, I think we could and should fix this in plotly.js since it will affect any Chromium user printing web pages and not just Orca.

**Comment by antoinerg** [comment] 2020-09-08 17:33
I tried to extract the ghost SVG element from a plotly.js figure and put it into a Codepen in order to reproduce the issue: https://codepen.io/antoinerg/full/MWyvQWx . I was hoping to see a think line when printing to PDF but alas, the rendering there is OK. I'm not sure what makes Chromium to render thin lines when printing plotly.js figure to PDF :confused:

**Comment by antoinerg** [comment] 2020-11-20 15:52
Closed by https://github.com/plotly/plotly.js/issues/5282

**Closed by antoinerg** 2020-11-20 15:52 UTC
