### ISSUE TITLE
Document imageserver image name for maintenance release

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/orca#173] opened 2018-12-19 20:20 UTC
All imageserver work for On-Prem 2.5.0 lands on https://github.com/plotly/orca/tree/v1.0.0-onprem. In order to make a maintenance release, we need some way to have a unique name for the updated image. 

**Suggestions:** 

1) Create a new branch for maintenance release v1.0.1-onprem
2) Tag image in quay. 

Option 2 seems to be a nice solution imo. 

I think we should document this for future releases. 

@plotly/devops

**Comment by scjody** [comment] 2018-12-19 20:35
Managing ORCA versions is up to the folks that work on ORCA: @etpinard and now @antoinerg. For 2.5.0 @etpinard created the `v1.0.0-onprem` tag, and I'm not sure what his plans were for maintenance releases.

Maintenance releases need to be based on the previous version (`v1.0.0-onprem` in this case) and need to contain _only_ the needed fix(es). So normally they'd be built from a maintenance branch (the devops team uses branches of the form `2.5-release`).

**Comment by scjody** [comment] 2018-12-19 21:34
@BRONSOLO and I investigated this together. It turns out that `v1.0.0-onprem` is a branch in GitHub, not a tag. When https://github.com/plotly/orca/pull/151 was merged to the `v1.0.0-onprem` Orca branch, CircleCI built the a Docker image, pushed it to Quay, and [tagged it as `v1.0.0-onprem`](https://github.com/plotly/orca/blob/eda04a4b0e6b0eba03d38b3ece79f281fb625fab/.circleci/config.yml#L127-L133).

As of this point, any customers who performed a new installation of 2.5.x or updated to any 2.5.x release ended up using the new Orca release rather than the one we were previously shipping. We don't want to do this - Orca releases should be tested as part of an overall On-Prem release before being sent to customers - but by the time we realized the error @BRONSOLO _had_ tested the new On-Prem maintenance release (including the new Orca release). We therefore decided to leave the `v1.0.0-onprem` tag as-is in Quay until we could discuss things in this issue.

(We have created a `v1.0.1-onprem` tag pointing to the new Orca, which @BRONSOLO will use as part of the 2.5.3 maintenance release he's putting out right now.)

Here's what things looked like before yesterday:

![screen shot 2018-12-19 at 16 18 05](https://user-images.githubusercontent.com/1136329/50248632-aee35080-03a9-11e9-83af-fbd33b0198c3.png)

Here's what things looked like yesterday:

![screen shot 2018-12-19 at 16 21 13](https://user-images.githubusercontent.com/1136329/50248769-22855d80-03aa-11e9-8b2b-bed6124244e1.png)

Here's what we actually wanted to happen:

![screen shot 2018-12-19 at 16 20 30](https://user-images.githubusercontent.com/1136329/50248733-0681bc00-03aa-11e9-8b81-eacc982ff8f7.png)

### How do we get there from here?

(and also prevent future merges in Orca from updating live On-Prem releases)

1. Create a new `v1.0-onprem` branch of Orca based on `v1.0.0-onprem` and push to GitHub.

2. Delete the `v1.0.0-onprem` branch from GitHub.

3. Tag the tip of that branch as `v1.0.1-onprem`.

4. Tag release https://github.com/plotly/orca/commit/4bb71b82600fa66463a0820b2e28e80bb2dc50b9 in GitHub as `v1.0.0-onprem`.

5. Tag the corresponding image in Quay (which is currently tagged as `4bb71b82600fa66463a0820b2e28e80bb2dc50b9` to match the git sha) as `v1.0.0-onprem`.

6. For the future, document a process for On-Prem releases in https://github.com/plotly/orca/blob/master/CONTRIBUTING.md:
    * For major On-Prem releases, create a _branch_ with a name of the form `v1.0-onprem` and a _tag_ (in GitHub and Quay of the form `v1.0.0-onprem`.
    * For On-Prem maintenance releases, create a tag of the form `v1.0.1-onprem`.

@plotly/devops @etpinard @antoinerg Does this sound reasonable to everyone?

**Comment by etpinard** [comment] 2018-12-19 23:30
Minor details: 

- the public version of orca is at `v1.1.1`, I think we should freeze it as `v1.1.1-onprem`
- like @BRONSOLO, I would prefer git tags to freeze onprem orca versions, but branches are :ok_hand: too
- I tried to auto-tag docker images pushed to Quay.io whenever we publish a new public orca release (see https://github.com/plotly/orca/issues/106), but my first attempt failed. Once we have that setup, we could then make onprem point to the corresponding tagged docker image with no extra work required.

**Comment by antoinerg** [comment] 2018-12-20 00:05
@BRONSOLO I think all the Docker images pushed to Quay already have a unique name. As you can see below they're tagged with the SHA1 of the commit (along with the branch name and the git tag): https://github.com/plotly/orca/blob/eda04a4b0e6b0eba03d38b3ece79f281fb625fab/.circleci/config.yml#L124-L134

**Comment by scjody** [comment] 2018-12-20 16:41
@etpinard @antoinerg It sounds like we're in agreement on using tags, not branches. I don't know why a branch was used for `v1.0.0-onprem` but let's focus on preventing this from happening again by agreeing on a process and documenting it.

We do tag Docker images with the git SHA1 and the name of the branch. I don't want to introduce any more automation than this - it's helpful to have humans involved when deciding what to release.

Here's what I propose (this is what the devops team does for all the images we manage):
* For major releases, create a release branch (e.g. `1.0-release` or `1.0-onprem` - the specifics of the branch name aren't that imporant but it's good to be consistent). For maintenance releases, use an existing release branch.
* CircleCI will automatically build Docker images for anything that's pushed to that branch.
* @etpinard or @antoinerg tags an image in Quay (with tags of the form `1.0.0-onprem` or `1.0.1-onprem` - again the specifics don't matter) and provides that to whoever on the devops team is working on the release.
* The devops team takes it from there (we put this tag into the Replicated YAML, test, and hopefully release).
* If we find an Orca bug that needs a new build, you provide us with a new Docker image tag for that build - tags don't get reused, to ensure that On-Prem builds are reproducible.

Does that sound OK? If so I suggest @etpinard or @antoinerg add this process to CONTRIBUTING and have me review the PR, just to make sure we're all on the same page.

@antoinerg I'll invite you to Quay.

Also I'll deal with the cleanup discussed in https://github.com/plotly/orca/issues/173#issuecomment-448751778.

**Comment by mag009** [comment] 2018-12-20 20:00
> @etpinard @antoinerg It sounds like we're in agreement on using tags, not branches. I don't know why a branch was used for `v1.0.0-onprem` but let's focus on preventing this from happening again by agreeing on a process and documenting it.
> 
> We do tag Docker images with the git SHA1 and the name of the branch. I don't want to introduce any more automation than this - it's helpful to have humans involved when deciding what to release.
> 
> Here's what I propose (this is what the devops team does for all the images we manage):
> 
> * For major releases, create a release branch (e.g. `1.0-release` or `1.0-onprem` - the specifics of the branch name aren't that imporant but it's good to be consistent). For maintenance releases, use an existing release branch.
> * CircleCI will automatically build Docker images for anything that's pushed to that branch.
> * @etpinard or @antoinerg tags an image in Quay (with tags of the form `1.0.0-onprem` or `1.0.1-onprem` - again the specifics don't matter) and provides that to whoever on the devops team is working on the release.
> * The devops team takes it from there (we put this tag into the Replicated YAML, test, and hopefully release).
> * If we find an Orca bug that needs a new build, you provide us with a new Docker image tag for that build - tags don't get reused, to ensure that On-Prem builds are reproducible.
> 
> Does that sound OK? If so I suggest @etpinard or @antoinerg add this process to CONTRIBUTING and have me review the PR, just to make sure we're all on the same page.
> 
> @antoinerg I'll invite you to Quay.
> 
> Also I'll deal with the cleanup discussed in [#173 (comment)](https://github.com/plotly/orca/issues/173#issuecomment-448751778).

For cloud, we use the master tag : https://github.com/plotly/orca/blob/eda04a4b0e6b0eba03d38b3ece79f281fb625fab/deployment/kube/prod/frontend.yaml#L56

 We should change that to use the SHA1. We rely on the auto-scale to migrate to the new image.

@scjody 
 We should probably provide a better way to deploy to cloud for helm (plotbot or circle)

**Comment by antoinerg** [comment] 2018-12-20 23:08
> For cloud, we use the master tag :
https://github.com/plotly/orca/blob/eda04a4b0e6b0eba03d38b3ece79f281fb625fab/deployment/kube/prod/frontend.yaml#L56
We should change that to use the SHA1. We rely on the auto-scale to migrate to the new image.

@mag009 Thank you for clearly reporting this issue that I briefly mentionned to @scjody yesterday. I agree that we should absolutely use a unique tag `image-exporter:$UNIQUE_TAG` or even better a digest `image-exporter@DIGEST`. I also think that this configuration file should probably be in its own private repo.

@scjody Is there a reason why we're keeping the `deployment` folder in the public repo?

Finally, about the Docker image's tags: do you like the idea of clearly distinguishing git tags from git branches by naming them:
``` bash
docker push quay.io/plotly/image-exporter:branch-$CIRCLE_BRANCH
docker push quay.io/plotly/image-exporter:tag-$CIRCLE_TAG
```
This would prevent any further confusion.

**Comment by scjody** [comment] 2018-12-20 23:37
@mag009 @antoinerg 

Let's discuss your concerns about Orca versioning for Chart Studio Cloud in a separate issue (probably in the streambed repo) - I'd like to keep this one focused on the On-Prem process.

>  We should probably provide a better way to deploy to cloud for helm (plotbot or circle)

Currently deployment happens via @plotbot, similarly to the way streambed is deployed. I'm not sure what improvements you have in mind but let's discuss them in a separate issue as well.

> Is there a reason why we're keeping the deployment folder in the public repo?

There's nothing confidential in that folder and it's helpful to keep everything related to Orca in one place, especially when making a PR that affects both what's being deployed (e.g. the `Dockerfile`) and how the deployment is done (e.g. the Kubernetes YAML).

> do you like the idea of clearly distinguishing git tags from git branches by naming them

That's an interesting idea (essentially Hungarian Notation for tags) but I still see the possibility for errors, especially considering whoever adds the tag in Quay would have to remember to add the `tag` prefix to it. Since this is different from the way every other project I've ever worked on handles branch and tag names, I think this will only lead to more confusion.

**Comment by antoinerg** [comment] 2018-12-21 01:41
> Let's discuss your concerns about Orca versioning for Chart Studio Cloud in a separate issue (probably in the streambed repo) 

Excellent idea

> There's nothing confidential in that folder and it's helpful to keep everything related to Orca in one place, especially when making a PR that affects both what's being deployed (e.g. the Dockerfile) and how the deployment is done (e.g. the Kubernetes YAML).

I can see the value of that. I think @etpinard also agrees with you.

> That's an interesting idea (essentially Hungarian Notation for tags) but I still see the possibility for errors, especially considering whoever adds the tag in Quay would have to remember to add the tag prefix to it. 

@scjody I'm not sure completely understand your point. My thoughts was that if we have a human operation of adding a tag on Quay, we should have a way of distingushing those tags from the ones created by the CI to prevent any collision/confusion. The convention could be that tags without a prefix are the ones created and approved by a human for deployment. This seems less error-prone to me but I may be wrong. The names could be 
``` bash
docker push quay.io/plotly/image-exporter:circleci-tag-$CIRCLE_TAG
```
to even better identify the images in our registry.

**Comment by scjody** [comment] 2018-12-21 18:05
I've performed the actions listed in https://github.com/plotly/orca/issues/173#issuecomment-448751778 other than the documentation change (I'll continue that discussion when I have time).

**Comment by antoinerg** [comment] 2020-01-21 20:26
After going smoothly through several releases since this issue was opened, I think we can close it. Please feel free to reopen if necessary.

**Closed by antoinerg** 2020-01-21 20:26 UTC
Labels: type: documentation
