### ISSUE TITLE
GL_INVALID_OPERATION errors

### ISSUE THREAD

**Issue by malmaud** [plotly/orca#97] opened 2018-06-25 15:24 UTC
Hi,
Thanks for this great tool! 

I'm seeing the following:

```
In [6]: from subprocess import call
   ...: import json
   ...:
   ...: fig = {"data": [{"y": [1,2,1]}]}
   ...: call(['orca', 'graph', json.dumps(fig), '-o', 'myfig.pdf', '--format', 'pdf'])
   ...:
   ...:
[43121:0625/111408.782905:ERROR:gles2_cmd_decoder.cc(17766)] [.RenderCompositor-0x7fb7e4022000]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[43121:0625/111408.783020:ERROR:gles2_cmd_decoder.cc(17766)] [.RenderCompositor-0x7fb7e4022000]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[43121:0625/111408.783125:ERROR:gles2_cmd_decoder.cc(4395)] [.RenderWorker-0x7fb7e500c200.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[43121:0625/111408.783161:ERROR:gles2_cmd_decoder.cc(4395)] [.RenderWorker-0x7fb7e500c200.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[43121:0625/111408.783182:ERROR:gles2_cmd_decoder.cc(4395)] [.RenderWorker-0x7fb7e500c200.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
[43121:0625/111408.783204:ERROR:gles2_cmd_decoder.cc(4395)] [.RenderWorker-0x7fb7e500c200.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[43121:0625/111408.783228:ERROR:gles2_cmd_decoder.cc(4395)] [.RenderWorker-0x7fb7e500c200.GpuRasterization]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
```

The errors appear harmless, though, as `myfig.pdf` is still successfully generated. As far as I can tell, the pdf is valid and looks fine.

Environment:

Python 3.6.5
OS X 10.13.5

Orca was installed  with `~ $ npm install -g electron@1.8.4 orca` just now.

**Comment by etpinard** [comment] 2018-12-28 19:40
Probably a duplicate of https://github.com/plotly/orca/issues/127

@malmaud have you tried adding `--enable-webgl` flag?

**Comment by etpinard** [comment] 2019-01-10 23:01
Closing / merging with #127 due to lack of activity.

**Closed by etpinard** 2019-01-10 23:01 UTC
